#define X_STICK_INPUT_PIN 13
#define Y_STICK_INPUT_PIN 14
#define SW_STICK_INPUT_PIN 12

#define IN1_DRIVER_PIN 6
#define IN2_DRIVER_PIN 5
#define IN3_DRIVER_PIN 4
#define IN4_DRIVER_PIN 3

#define ENA_DRIVER_PIN 7
#define ENB_DRIVER_PIN 2